import { readFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import ts from "typescript";
import { marker } from "./codemod.mjs";

export async function readOptional(file) {
  try { return await readFile(file, "utf8"); }
  catch (error) { if (error.code === "ENOENT") return null; throw error; }
}

// Never import/evaluate the consumer's configuration. Accept only the data-only
// form generated by the CLI, including the existing 0.3.3 format.
export function parseManagedConfig(source, validate) {
  const invalid = () => new Error(".kue/config.js is not a valid managed configuration. Restore the generated file or maintain KUE manually; it will not be executed or silently reset.");
  if (!source.trimStart().startsWith(marker)) throw invalid();
  const file = ts.createSourceFile("config.js", source, ts.ScriptTarget.Latest, true, ts.ScriptKind.JS);
  const statement = file.statements[0];
  if (file.parseDiagnostics.length || file.statements.length !== 1 || !statement || !ts.isVariableStatement(statement) ||
      statement.modifiers?.length !== 1 || statement.modifiers[0].kind !== ts.SyntaxKind.ExportKeyword ||
      !(statement.declarationList.flags & ts.NodeFlags.Const) || statement.declarationList.declarations.length !== 1) throw invalid();
  const declaration = statement.declarationList.declarations[0];
  if (!ts.isIdentifier(declaration.name) || declaration.name.text !== "kueCloudConfig" ||
      !declaration.initializer || !ts.isObjectLiteralExpression(declaration.initializer)) throw invalid();
  const props = declaration.initializer.properties;
  if (props.length !== 2 || props.some(prop => !ts.isPropertyAssignment(prop) || !ts.isStringLiteral(prop.name) || !ts.isStringLiteral(prop.initializer)) ||
      new Set(props.map(prop => prop.name.text)).size !== 2) throw invalid();
  try {
    const value = JSON.parse(declaration.initializer.getText(file));
    if (Object.keys(value).some(key => !["projectKey", "apiBaseUrl"].includes(key))) throw invalid();
    return validate(value);
  } catch { throw invalid(); }
}

export const configFingerprint = config => createHash("sha256").update(JSON.stringify(config)).digest("hex");
export function parseSetupState(source, config) {
  if (source === null) return { version: 1 };
  let state;
  try { state = JSON.parse(source); } catch { throw new Error("Invalid .kue/setup.json; restore or remove this metadata file before setup."); }
  const digest = value => typeof value === "string" && /^[a-f0-9]{64}$/u.test(value);
  if (!state || state.version !== 1 || Object.keys(state).some(key => !["version", "connection", "sdkTarball", "recording"].includes(key)) ||
      (state.connection !== undefined && (!state.connection || typeof state.connection.repository !== "string" ||
        !/^[\w-]+\/[\w.-]+$/u.test(state.connection.repository) || !digest(state.connection.configHash))) ||
      (state.sdkTarball !== undefined && (!state.sdkTarball || !digest(state.sdkTarball.sha256) || typeof state.sdkTarball.version !== "string")) ||
      (state.recording !== undefined && (!state.recording || !["auto", "off"].includes(state.recording.mode) ||
        typeof state.recording.nativeEnabled !== "boolean" || !digest(state.recording.configHash) ||
        (state.recording.mode === "off" && state.recording.nativeEnabled)))) {
    throw new Error("Invalid .kue/setup.json; restore or remove this metadata file before setup.");
  }
  // Metadata is only a local hint; never treat it as Cloud authorization. An
  // independently replaced config must not inherit the old repository identity.
  if (!config || state.connection?.configHash !== configFingerprint(config)) delete state.connection;
  return state;
}
